language: java

script: mvn package

deploy:
  provider: heroku
  api_key:
    secure: RGUVpyl9vPnjzgc3wrqc7UlKn9cEA9MoKh/72u7/G4VVTglerLLUgHEKgM+dYXwtsZunvMNMjJgE+GuPV7tYl9FP+ANTE1EfsUrb1QwGRSYCFhIhCYDgJwjEUtL+MAkAzZuIashrYj/V+ToMc94zogHQ6E8PN4Qzkl9WEVwB3SWkNd7jhspAFvWbJ886tTOBDa/pK249ccXkSlcbPs6J7d8oY8+CDfb4ef8/ssohI5xbL9bjsjQvLi5+EpXTymwRPH9Sl4i0hTB5CsgAu3b3nJkawVNS2wmGXPw/dd2DD9VY1BXB5QkF2PKATTHFRl+q9dfHSLexJPrQpF7O8LJ6IW+TOtp18ttpTc3WD92rJgZzrllCiYapwPiHLZXzH4L9o7CgfwCXWVavVxuS8XDF5hcySMYHOhbEqx7cZVfzrwsOL57NUvRDmPydgXEyFpT7XwfhYqbdUeXZJAKExMmw4W7A1FKnwscLfxgKauF56cisqgGP1jhF32lcVpx4zb+x22r7EmA6xMHIjSeVyf5m3My4rSU0pSYQHfGEBMsWVxdFeDPy7p1b1oozyLf2K+vvzvKKbawIWuneNCDxPotENt4VFzSJUHCYgZLMbtgS0883Cd6zpECIr/UYd9oM93ybAn4bg38c0qCQrtbvcjD7/iDxqweAprVUedgOrpgL9Vs=
